"""add_soft_delete

Revision ID: 8f4a8f5f20af
Revises: add_valor_ultima_parcela
Create Date: 2026-04-30 00:52:00.773285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f4a8f5f20af'
down_revision: Union[str, Sequence[str], None] = 'add_valor_ultima_parcela'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recibos', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recibos', 'deleted_at')
    # ### end Alembic commands ###
