"""add idempotency key

Revision ID: c29e0a8ed969
Revises: 8f4a8f5f20af
Create Date: 2026-04-30 02:31:21.417036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c29e0a8ed969"
down_revision: Union[str, Sequence[str], None] = "8f4a8f5f20af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recibos", sa.Column("idempotency_key", sa.String(length=255), nullable=True)
    )
    op.create_index(
        op.f("ix_recibos_idempotency_key"), "recibos", ["idempotency_key"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recibos_idempotency_key"), table_name="recibos")
    op.drop_column("recibos", "idempotency_key")
    # ### end Alembic commands ###
